# Generated by Django 5.0.1 on 2025-09-30 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('origin_country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('lifespan', models.CharField(blank=True, max_length=20)),
                ('temperament', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('second_confidence', models.FloatField(blank=True, null=True)),
                ('third_confidence', models.FloatField(blank=True, null=True)),
                ('predicted_breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.dogbreed')),
                ('second_breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_breed_predictions', to='classifier.dogbreed')),
                ('third_breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_breed_predictions', to='classifier.dogbreed')),
            ],
        ),
    ]
