# Generated by Django 5.2.6 on 2025-09-30 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogbreed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='lifespan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='temperament',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='second_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_breed_predictions', to='classifier.dogbreed'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='second_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='third_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_breed_predictions', to='classifier.dogbreed'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='third_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
