stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker info

test:
  stage: test
  image: python:3.11
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - cd dog_breed_identifier
    - python manage.py check
  only:
    - main

build:
  stage: build
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $DOCKER_USERNAME/dog-breed-identifier:latest .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/dog-breed-identifier:latest
  only:
    - main

deploy-render:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - curl -X POST $RENDER_DEPLOY_HOOK
  only:
    - main
  when: manual