version: 1
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/dogbreeddb
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dogbreeddb
      MYSQL_USER: dogbreeduser
      MYSQL_PASSWORD: dogbreedpass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: